# Generated by Django 4.0.1 on 2022-04-17 17:44

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, choices=[('High Scool Certificate', 'High Scool Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters')], default='None', max_length=30, null=True)),
                ('skills_req', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Permanent', 'Permanent'), ('Internship', 'Internship'), ('Attachment', 'Attachment')], default='Full Time', max_length=30, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, null=True, populate_from='title', unique=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('filled', models.BooleanField(default=False)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_posted',),
            },
        ),
        migrations.CreateModel(
            name='Selected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_applicant', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_job', to='recruiters.job')),
            ],
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='recruiters.job')),
            ],
        ),
    ]
