# Generated by Django 4.0.1 on 2022-04-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
