# Generated by Django 4.0.1 on 2022-03-02 12:17

from django.db import migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
    ]
