# Generated by Django 4.0.1 on 2022-03-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(blank=True, choices=[('High Scool Certificate', 'High Scool Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters')], default='Full Time', max_length=30, null=True),
        ),
    ]
