# Generated by Django 4.0.1 on 2022-03-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_job_experience_job_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
