# Generated by Django 4.0.1 on 2022-03-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0005_alter_job_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-date_posted',)},
        ),
    ]
