# Generated by Django 4.0.1 on 2022-03-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0006_alter_job_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(blank=True, choices=[('High Scool Certificate', 'High Scool Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters')], default='None', max_length=30, null=True),
        ),
    ]
