# Generated by Django 4.0.1 on 2022-03-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0007_alter_job_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Permanent', 'Permanent'), ('Internship', 'Internship'), ('Attachment', 'Attachment')], default='Full Time', max_length=30, null=True),
        ),
    ]
