# Generated by Django 4.0.1 on 2022-04-18 13:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='user', unique=True),
        ),
    ]
